const OK = 200;
const CREATED = 201;
const BAD_REQUEST_ERR = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN_ERR = 403;
const NOT_FOUND_ERR = 404;
const INTERNAL_SERVER_ERR = 500;
const CONFLICT = 409;

const SALT_ROUNDS = 10;

module.exports = {
  OK,
  CREATED,
  BAD_REQUEST_ERR,
  UNAUTHORIZED,
  FORBIDDEN_ERR,
  NOT_FOUND_ERR,
  INTERNAL_SERVER_ERR,
  CONFLICT,
  SALT_ROUNDS,
};
